name: Daily snap build

on:
  schedule:
    # Run every 24 hours, at 4:30 UTC.
    # SVN imports in https://github.com/0ad/0ad/ happen daily at 4:00 UTC.
    - cron: '30 4 * * *'
  # Allow running manually, for testing purposes.
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  daily-snap:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: snapcore/action-build@v1
        id: build-new-snap-daily
      - uses: snapcore/action-publish@master
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_LOGIN }}
        with:
          snap: ${{ steps.build-new-snap-daily.outputs.snap }}
          release: edge
